package com.zice.xz.greendao;

import java.util.List;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.query.Query;
import org.greenrobot.greendao.query.QueryBuilder;

import com.zice.xz.dataentity.ConsumeType;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "CONSUME_TYPE".
*/
public class ConsumeTypeDao extends AbstractDao<ConsumeType, Long> {

    public static final String TABLENAME = "CONSUME_TYPE";

    /**
     * Properties of entity ConsumeType.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Index = new Property(0, Long.class, "index", false, "INDEX");
        public final static Property TypeId = new Property(1, Long.class, "typeId", true, "_id");
        public final static Property CategoryId = new Property(2, Long.class, "categoryId", false, "category_id");
        public final static Property TypeName = new Property(3, String.class, "typeName", false, "type_name");
        public final static Property Desc = new Property(4, String.class, "desc", false, "desc");
    }

    private DaoSession daoSession;

    private Query<ConsumeType> consumeCategory_ConsumeTypesQuery;

    public ConsumeTypeDao(DaoConfig config) {
        super(config);
    }
    
    public ConsumeTypeDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"CONSUME_TYPE\" (" + //
                "\"INDEX\" INTEGER," + // 0: index
                "\"_id\" INTEGER PRIMARY KEY ," + // 1: typeId
                "\"category_id\" INTEGER," + // 2: categoryId
                "\"type_name\" TEXT," + // 3: typeName
                "\"desc\" TEXT);"); // 4: desc
        // Add Indexes
        db.execSQL("CREATE UNIQUE INDEX " + constraint + "IDX_CONSUME_TYPE_INDEX ON \"CONSUME_TYPE\"" +
                " (\"INDEX\" ASC);");
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"CONSUME_TYPE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, ConsumeType entity) {
        stmt.clearBindings();
 
        Long index = entity.getIndex();
        if (index != null) {
            stmt.bindLong(1, index);
        }
 
        Long typeId = entity.getTypeId();
        if (typeId != null) {
            stmt.bindLong(2, typeId);
        }
 
        Long categoryId = entity.getCategoryId();
        if (categoryId != null) {
            stmt.bindLong(3, categoryId);
        }
 
        String typeName = entity.getTypeName();
        if (typeName != null) {
            stmt.bindString(4, typeName);
        }
 
        String desc = entity.getDesc();
        if (desc != null) {
            stmt.bindString(5, desc);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, ConsumeType entity) {
        stmt.clearBindings();
 
        Long index = entity.getIndex();
        if (index != null) {
            stmt.bindLong(1, index);
        }
 
        Long typeId = entity.getTypeId();
        if (typeId != null) {
            stmt.bindLong(2, typeId);
        }
 
        Long categoryId = entity.getCategoryId();
        if (categoryId != null) {
            stmt.bindLong(3, categoryId);
        }
 
        String typeName = entity.getTypeName();
        if (typeName != null) {
            stmt.bindString(4, typeName);
        }
 
        String desc = entity.getDesc();
        if (desc != null) {
            stmt.bindString(5, desc);
        }
    }

    @Override
    protected final void attachEntity(ConsumeType entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1);
    }    

    @Override
    public ConsumeType readEntity(Cursor cursor, int offset) {
        ConsumeType entity = new ConsumeType( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // index
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // typeId
            cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2), // categoryId
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // typeName
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4) // desc
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, ConsumeType entity, int offset) {
        entity.setIndex(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setTypeId(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setCategoryId(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
        entity.setTypeName(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setDesc(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(ConsumeType entity, long rowId) {
        entity.setTypeId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(ConsumeType entity) {
        if(entity != null) {
            return entity.getTypeId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(ConsumeType entity) {
        return entity.getTypeId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "consumeTypes" to-many relationship of ConsumeCategory. */
    public List<ConsumeType> _queryConsumeCategory_ConsumeTypes(Long categoryId) {
        synchronized (this) {
            if (consumeCategory_ConsumeTypesQuery == null) {
                QueryBuilder<ConsumeType> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.CategoryId.eq(null));
                consumeCategory_ConsumeTypesQuery = queryBuilder.build();
            }
        }
        Query<ConsumeType> query = consumeCategory_ConsumeTypesQuery.forCurrentThread();
        query.setParameter(0, categoryId);
        return query.list();
    }

}
