package com.zice.xz.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.zice.xz.dataentity.ConsumeBill;
import com.zice.xz.dataentity.ConsumeCategory;
import com.zice.xz.dataentity.ConsumeType;

import com.zice.xz.greendao.ConsumeBillDao;
import com.zice.xz.greendao.ConsumeCategoryDao;
import com.zice.xz.greendao.ConsumeTypeDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig consumeBillDaoConfig;
    private final DaoConfig consumeCategoryDaoConfig;
    private final DaoConfig consumeTypeDaoConfig;

    private final ConsumeBillDao consumeBillDao;
    private final ConsumeCategoryDao consumeCategoryDao;
    private final ConsumeTypeDao consumeTypeDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        consumeBillDaoConfig = daoConfigMap.get(ConsumeBillDao.class).clone();
        consumeBillDaoConfig.initIdentityScope(type);

        consumeCategoryDaoConfig = daoConfigMap.get(ConsumeCategoryDao.class).clone();
        consumeCategoryDaoConfig.initIdentityScope(type);

        consumeTypeDaoConfig = daoConfigMap.get(ConsumeTypeDao.class).clone();
        consumeTypeDaoConfig.initIdentityScope(type);

        consumeBillDao = new ConsumeBillDao(consumeBillDaoConfig, this);
        consumeCategoryDao = new ConsumeCategoryDao(consumeCategoryDaoConfig, this);
        consumeTypeDao = new ConsumeTypeDao(consumeTypeDaoConfig, this);

        registerDao(ConsumeBill.class, consumeBillDao);
        registerDao(ConsumeCategory.class, consumeCategoryDao);
        registerDao(ConsumeType.class, consumeTypeDao);
    }
    
    public void clear() {
        consumeBillDaoConfig.clearIdentityScope();
        consumeCategoryDaoConfig.clearIdentityScope();
        consumeTypeDaoConfig.clearIdentityScope();
    }

    public ConsumeBillDao getConsumeBillDao() {
        return consumeBillDao;
    }

    public ConsumeCategoryDao getConsumeCategoryDao() {
        return consumeCategoryDao;
    }

    public ConsumeTypeDao getConsumeTypeDao() {
        return consumeTypeDao;
    }

}
